---
language: node_js
node_js:
  - 4
  - stable
cache:
  yarn: true
  directories:
    - node_modules
env:
  - NODE_ENV=development
  - NODE_ENV=production
matrix:
  fast_finish: true
install:
  - NODE_ENV=development yarn install
before_script:
  - if [ "${NODE_ENV}" = "production" ]; then yarn build; fi
script:
  - yarn lint
  - if [ "${NODE_ENV}" = "production" ]; then yarn test; fi
  - if [ "${NODE_ENV}" = "development" ]; then AST_COMPARE=1 yarn test --runInBand; fi
  - if [ "${NODE_ENV}" = "development" ]; then yarn codecov; fi
branches:
  only:
    - master